(function(_ds){var window=this;var jEa=function(a){const b=a.yE,c=a.Fd,d=a.wA;a=a.sC;let e;e='<ul class="devsite-nav-list"><li class="devsite-nav-item devsite-nav-heading devsite-toc-toggle"><span class="devsite-nav-title" role="heading" aria-level="2"><span class="devsite-nav-text">Nesta p\u00e1gina</span></span>';c&&(e=e+'<button type="button" title="'+_ds.ZC("Expandir/recolher conte\u00fado"),e+='" class="devsite-nav-show-all button-transparent material-icons"></button>');e+="</li>";const f=b.length;for(let h=0;h<f;h++){var g=
b[h];e+='<li class="devsite-nav-item"'+(c&&g.index<a?" visible":"")+'><a href="#'+_ds.T(g.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.T(h)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+_ds.T(h)+'" track-metadata-link-destination="#'+_ds.T(g.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.S(g.text)+"</span></a>";
if(g.children.length){e+='<ul class="devsite-nav-list">';g=g.children;const k=g.length;for(let l=0;l<k;l++){const m=g[l];e+='<li class="devsite-nav-item"'+(c&&m.index<a?" visible":"")+'><a href="#'+_ds.T(m.id)+'" class="devsite-nav-title gc-analytics-event" data-category="Site-Wide Custom Events" data-action="click" data-label="'+(c?"Embedded nav":"Right nav")+'" data-value="'+_ds.T(h)+"."+_ds.T(l)+'" track-type="navigation" track-name="'+(c?"embeddedNav":"rightNav")+'" track-metadata-position="'+
_ds.T(h)+"."+_ds.T(l)+'" track-metadata-link-destination="#'+_ds.T(m.id)+'"><span class="devsite-nav-text" tooltip>'+_ds.S(m.text)+"</span></a></li>"}e+="</ul>"}e+="</li>"}d&&(e=c?e+'<li class="devsite-nav-item devsite-apix-link"><a href="#try-it" class="devsite-nav-title"><span class="devsite-nav-text" tooltip>Testar</span></a></li>':e+'<button type="button" class="devsite-show-apix button-primary">Testar</button>');c&&(e=e+'<li class="devsite-toc-toggle"><button type="button" class="button-flat devsite-nav-more-items material-icons" track-type="navigation" track-name="embeddedNavExpand" title="'+
_ds.ZC("Expandir/recolher conte\u00fado"),e+='"></button></li>');return(0,_ds.P)(e+"</ul>")};var X8=function(a){if(!a.hasAttribute("disabled")){var b=document.querySelector("devsite-content .devsite-article-body");b?(a.Fd?a.classList.add("devsite-toc-embedded"):a.classList.add("devsite-toc"),kEa(a,b),a.ra=!0):a.hide()}},mEa=async function(a){await lEa(a);if(a.j){var b=`#${a.j.id}`,c=encodeURI(b);b=a.oa.get(b)||a.oa.get(c);a.o!==b&&(a.o&&a.o.classList.remove("devsite-nav-active"),b&&(b.classList.add("devsite-nav-active"),a.qa&&("scrollIntoViewIfNeeded"in b?b.scrollIntoViewIfNeeded():b.scrollIntoView()),
a.o=b))}},nEa=function(a){a.Fd||a.eventHandler.listen(document.body,"devsite-content-updated devsite-element-hidden devsite-element-visible devsite-page-loaded devsite-sticky-resize devsite-sticky-scroll".split(" "),()=>{a.Ba.Ua()});a.eventHandler.listen(document.body,"devsite-content-updated",()=>{X8(a)})},oEa=async function(a){if("IntersectionObserver"in _ds.Cg()){a.Ob&&a.Ob.disconnect();var b=document.querySelector("devsite-header");let c=152;b&&(await customElements.whenDefined("devsite-header"),
(b=b.m+b.j)&&(c=b));a.Ob=new IntersectionObserver(d=>{for(const e of d)e.isIntersecting?a.ea.add(e.target):a.ea.delete(e.target);a.Ba.Ua()},{rootMargin:`${c}px 0px 0px 0px`,threshold:[0,1]})}a.va.resolve()},lEa=async function(a){let b=0;var c=document.querySelector("devsite-header");c&&(await customElements.whenDefined("devsite-header"),b=_ds.AQ(c));c=a.m.findIndex(e=>a.ea.has(e)&&e.getBoundingClientRect().top>=b);const d=a.m[c];if(d){const e=await pEa();d.getBoundingClientRect().top-b>e&&c>0?a.j=
a.m[c-1]:a.j=d}else a.j&&a.j.getBoundingClientRect().top>window.innerHeight&&(c=a.m.indexOf(a.j),c>0&&(a.j=a.m[c-1]))},kEa=function(a,b){const c=[];let d=!1,e="";switch(a.getAttribute("depth")){case "1":e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents)";break;default:e="h2:not(.hide-from-toc):not(#contents):not(#table-of-contents), h3:not(.hide-from-toc):not(#contents):not(#table-of-contents)"}a.m=[...b.querySelectorAll(e)].filter(f=>f.id&&f.dataset.text).filter(f=>{const g=[document.body.hasAttribute("free-trial")?
".ineligible":".eligible",".ds-selector-tabs,.kd-tabbed-horz,devsite-selector,.devsite-dialog"].join();return f.closest(g)?!1:!0});for(const [f,g]of a.m.entries())b=g,b={id:b.id,level:b.tagName.toLowerCase(),text:b.dataset.text,children:[],index:f},b.level==="h2"?(c.push(b),d=!0):d?c[c.length-1].children.push(b):c.push(b);_ds.yb(a.ua,c,a.xa.bind(a))&&a.ra||(c.length?(qEa(a,c),a.show(),a.Fd||rEa(a)):a.hide(),a.ua=c)},qEa=function(a,b){const c=_ds.Gt(jEa,{yE:b,Fd:a.Fd,wA:!!document.body.querySelector("devsite-apix, .devsite-apix"),
sC:b.length<8?8:5});if(a.qa)(b=c.querySelector("button.devsite-show-apix"))&&a.eventHandler.listen(b,"click",()=>{a.dispatchEvent(new CustomEvent("devsite-concierge-open-panel",{bubbles:!0,composed:!0,detail:{hs:"devsite-concierge-api-explorer-panel"}}))});else{b=document.querySelector("button.devsite-show-apix");const e=document.querySelector("devsite-apix");var d=!(e==null?0:e.querySelector("div.devsite-apix"));b&&e&&d&&a.eventHandler.listen(b,"click",()=>{e.scrollIntoView()})}b=c.querySelectorAll("a.devsite-nav-title");
for(const e of b){b=e;d=b.hash;const f=encodeURI(b.hash);a.oa.set(d,b);a.oa.set(f,b)}_ds.Pn(a);a.Fd&&_ds.cn(a,"hidden","",c);a.appendChild(c);if(a.Fd){if(a.getElementsByClassName("devsite-nav-item").length>8){for(const e of a.querySelectorAll(".devsite-nav-show-all, .devsite-nav-more-items"))a.eventHandler.listen(e,"click",()=>{a.hasAttribute("expanded")?a.removeAttribute("expanded"):_ds.cn(a,"expanded","")});_ds.cn(a,"expandable","")}else a.removeAttribute("expandable");setTimeout(()=>{c.removeAttribute("hidden")},
0)}},rEa=async function(a){await a.va.promise;if(a.Ob){a.Ob.disconnect();a.ea.clear();a.o&&a.o.classList.remove("devsite-nav-active");a.o=null;for(const b of a.m)a.Ob.observe(b)}},pEa=async function(){let a=0,b=0;const c=document.querySelector("devsite-header");c&&(await customElements.whenDefined("devsite-header"),a=_ds.AQ(c),b=c.m+c.j);return Math.max(b-a,Math.floor((window.innerHeight-a)/5))},Y8=class extends _ds.fn{static get observedAttributes(){return["max-height","offset"]}constructor(){super();
this.eventHandler=new _ds.v;this.va=new _ds.Oh;this.ea=new Set;this.oa=new Map;this.Aa=new _ds.fi(()=>void X8(this),16);this.Ba=new _ds.fi(()=>void mEa(this),33);this.j=this.o=null;this.m=[];this.ra=!1;this.Ob=null;this.qa=this.Fd=!1;this.ua=[];_ds.bn(this,(0,_ds.Fg)`disabled`,(0,_ds.Fg)`has-sidebar`,(0,_ds.Fg)`hidden`,(0,_ds.Fg)`expandable`,(0,_ds.Fg)`expanded`,(0,_ds.Fg)`visible`)}connectedCallback(){this.Fd=this.hasAttribute("devsite-toc-embedded");this.qa=document.body.hasAttribute("concierge");
X8(this);nEa(this)}disconnectedCallback(){this.hide();this.ra=!1;_ds.G(this.eventHandler)}fn(a){a=a&&a.toLowerCase()==="false";this.ua=[];_ds.Pn(this);a?(_ds.cn(this,"disabled",""),this.hide()):(this.removeAttribute("disabled"),this.Aa.Ua())}hide(){_ds.Pn(this);this.dispatchEvent(new CustomEvent("devsite-element-hidden",{bubbles:!0}));this.removeAttribute("visible");_ds.cn(this,"hidden","");if(!this.Fd){const a=document.querySelector(".devsite-sidebar"),b=document.querySelector(".devsite-main-content");
(a==null?0:a.contains(this))&&b&&b.removeAttribute("has-sidebar")}}show(){this.dispatchEvent(new CustomEvent("devsite-element-visible",{bubbles:!0}));this.removeAttribute("hidden");_ds.cn(this,"visible","");if(!this.Fd){const a=document.querySelector(".devsite-sidebar"),b=document.querySelector(".devsite-main-content");(a==null?0:a.contains(this))&&b&&_ds.cn(this,"has-sidebar","",b);oEa(this)}}xa(a,b){let c=!0;if(a.children.length||b.children.length)c=_ds.yb(a.children,b.children,this.xa.bind(this));
return c&&a.id===b.id&&a.text===b.text}};Y8.prototype.renderUpdatedContent=Y8.prototype.fn;Y8.prototype.disconnectedCallback=Y8.prototype.disconnectedCallback;Y8.prototype.connectedCallback=Y8.prototype.connectedCallback;try{customElements.define("devsite-toc",Y8)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteToc",a)};})(_ds_www);
