(function(_ds){var window=this;var Ira=function(){return(0,_ds.P)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},Jra=function(){return(0,_ds.P)('<div class="devsite-book-nav-blur"></div>')},Kra=function(a){a=a.JC;a=_ds.LQ(new _ds.bz("{NUMBER_OF_MATCHING_DESCENDANTS,plural, =1{{XXX_1} correspondente}one{{XXX_2} correspondente}other{{XXX_2} correspondentes}}"),{NUMBER_OF_MATCHING_DESCENDANTS:a,XXX_1:_ds.SC(_ds.jx(1)),XXX_2:_ds.SC(_ds.jx(a))});
return(0,_ds.P)('<span class="devsite-nav-filter-match-count"> (<mark>'+a+"</mark>)</span>")};var Lra="onpointerover"in window?"pointerover":"mouseover",C_=function(a){const b=a.querySelectorAll(".devsite-nav-item").length>0,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.cn(a,"visually-hidden","",c))},Mra=async function(a){a.classList.contains("hide-collapsed-panel")&&a.classList.remove("hide-collapsed-panel");var b=document.documentElement.scrollHeight-document.documentElement.clientHeight;const c=b?document.documentElement.scrollTop/b:
0;_ds.wq(a.eventHandler,a,_ds.ko,()=>{a.removeAttribute("animatable");a.background.removeAttribute("animatable");a.ea.removeAttribute("animatable")});_ds.cn(a,"animatable","");b=_ds.wg(a.ma`animatable`);b(a.background,"animatable","");b(a.ea,"animatable","");a.hasAttribute("collapsed")?(_ds.cn(a,"aria-label","Ocultar navega\u00e7\u00e3o lateral",a.j),_ds.cn(a,"data-title","Ocultar navega\u00e7\u00e3o lateral",a.j),a.removeAttribute("collapsed"),_ds.Sy(a.j,"expanded","true"),D_(a,"expandedLeftNav",
"Expanded book nav","click")):(_ds.cn(a,"aria-label","Mostrar navega\u00e7\u00e3o lateral",a.j),_ds.cn(a,"data-title","Mostrar navega\u00e7\u00e3o lateral",a.j),_ds.cn(a,"collapsed",""),_ds.Sy(a.j,"expanded","false"),D_(a,"collapsedLeftNav","Collapsed book nav","click"),_ds.wq(a.eventHandler,a,_ds.ko,()=>{a.classList.add("hide-collapsed-panel")}));await _ds.Vo();b=document.documentElement.scrollHeight-document.documentElement.clientHeight;document.documentElement.scrollTop=Math.round(c*b)},Nra=function(a){a.eventHandler.listen(a,
"click",b=>{const c=E_(a,b.target);c&&D_(a,"click",`Book nav link, pathname: ${c.href}`,void 0,{eventDetail:c.href});F_(a,b)});a.eventHandler.listen(a,"keypress",b=>{b.key==="Enter"&&F_(a,b)});a.eventHandler.listen(a,[Lra,"focusin"],b=>{b.defaultPrevented||(b=E_(a,b.target))&&_ds.ng(b,_ds.Oo(b.href).href)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",()=>{a.o&&(G_(a,"_book")?a.removeAttribute("top-level-nav"):_ds.cn(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",
()=>void a.xa.Ua());a.eventHandler.listen(a,"devsite-content-updated",()=>{a.xa.Ua()});a.eventHandler.listen(a,"scroll",()=>{_ds.cn(a,"user-scrolled","")});a.eventHandler.listen(a.j,"click",()=>{a.Ea.Ua()});a.m&&(a.eventHandler.listen(a.m,"keyup",()=>void a.Ba.Ua()),a.eventHandler.listen(a.m,"focus",()=>void H_(a,"focus")));a.qa&&a.eventHandler.listen(a.qa,["click","keydown"],b=>{if(b.type==="click"||b.key==="Enter"||b.key==="Escape"){a.m&&(a.m.value="",a.m.focus());let c;(c=a.qa)==null||c.classList.add("hidden");
I_(a);J_(a);H_(a,b.type)}})},K_=function(a,b=a,c=!0){b=Array.from(b.querySelectorAll(".devsite-nav-title"));a.oa=new Set(b);if(!_ds.u().hash&&c)Ora(a,a.oa);else{c=new _ds.bU;for(const d of a.oa)_ds.aU(c,d)}},L_=async function(a){const b=await _ds.w();for(const c of a.oa)b.unregisterIntersectionForElement(c)},E_=function(a,b){b=_ds.go(b,c=>c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a,!0);return b===a?null:b},D_=function(a,b,c,d,e){a.Da(Object.assign({},{category:"Site-Wide Custom Events",
action:d||b},c&&{label:c}));b=Object.assign({},{type:"bookNav",name:b},e&&{metadata:e});a.dispatchEvent(_ds.Sf(b))},F_=function(a,b){if(!b.defaultPrevented){var c=b.target;c.getAttribute("id")==="devsite-close-nav"&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.cn(a,"top-level-nav",""));if(c.hasAttribute("menu")){var d=c.getAttribute("menu");d&&G_(a,d)&&(b.preventDefault(),b.stopPropagation(),
a.scrollTop=0,a.removeAttribute("top-level-nav"))}var e=c.closest(".devsite-expandable-nav");if(e&&(d=c.closest(".devsite-nav-title, .devsite-nav-toggle"))){let f=b.target,g,h;if(!((g=f)==null?0:(h=g.closest(".devsite-nav-title"))==null?0:h.hasAttribute("href"))){for(b=b.type==="click"||b.type==="touchend";f&&f!==e;){if(f.classList.contains("devsite-nav-title-no-path")&&b){f.blur();break}f=f.parentNode}e.querySelector(".devsite-nav-section")&&(b=e.classList.toggle("expanded"),(e=e.querySelector(".devsite-nav-title"))&&
_ds.cn(a,"aria-expanded",`${b}`,e))}if(d.matches(".devsite-nav-toggle"))return}c.closest(".devsite-nav-title-no-path")||(a.o&&(d=a.o.querySelector("[menu=_book]"))&&d.contains(c)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})),(c=c.closest("a.devsite-nav-title"))&&!c.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})))}},H_=function(a,b){D_(a,b==="focus"?"filterInput":"filterClearButton",b==="focus"?"devsite-book-nav-filter input":
"devsite-book-nav-filter filter-clear-button",b)},M_=function(a){a.ua=Array.from(a.querySelectorAll(".devsite-mobile-nav-bottom .devsite-nav-list[menu=_book] .devsite-nav-item:not(.devsite-nav-heading)"))},O_=function(a){const b=_ds.u().searchParams.get("nf");a.m&&b&&(a.m.value=b,N_(a))},N_=function(a){if(a.ua.length){I_(a);J_(a);var b,c,d=(b=a.m)==null?void 0:(c=b.value)==null?void 0:c.trim().toLowerCase();if(d){var e;(e=a.qa)==null||e.classList.remove("hidden");for(const g of a.ua){var f=g.querySelectorAll(".devsite-nav-text");
a=g.classList.contains("devsite-nav-expandable");e=c=!1;b=0;let h,k,l;const m=((l=(h=g)==null?void 0:(k=h.getAttribute("data-synonyms"))==null?void 0:k.split(","))!=null?l:[]).some(r=>r.toLowerCase().includes(d));let n,q;if(d&&a&&(m||((n=g.querySelector(".devsite-nav-text"))==null?0:(q=n.textContent)==null?0:q.toLowerCase().includes(d))))e=c=!0;else for(const r of f){let A,F,K,Q;f=((Q=(A=r)==null?void 0:(F=A.parentElement)==null?void 0:(K=F.getAttribute("data-synonyms"))==null?void 0:K.split(","))!=
null?Q:[]).some(R=>R.toLowerCase().includes(d));if(d){let R;if(f||((R=r.textContent)==null?0:R.toLowerCase().includes(d)))c=!0,++b}}if(c===!0){g.classList.remove("hidden");if(e){c=Array.from(g.querySelectorAll(".devsite-nav-item"));for(const r of c){r.classList.remove("hidden");let A,F,K,Q;c=((Q=(A=r)==null?void 0:(F=A.parentElement)==null?void 0:(K=F.getAttribute("data-synonyms"))==null?void 0:K.split(","))!=null?Q:[]).some(O=>O.toLowerCase().includes(d));let R;d&&(c||((R=r.textContent)==null?0:
R.toLowerCase().includes(d)))&&++b}}Pra(g,d)}a&&b>0&&Qra(g,b)}}else(f=a.qa)==null||f.classList.add("hidden")}},I_=function(a){for(const b of a.ua){let c;b.classList.toggle("hidden",!((c=a.m)==null||!c.value))}},J_=function(a){if(a.querySelector("mark")){var b=[...a.querySelectorAll(".devsite-nav-text > .devsite-nav-filter-match-count")];for(const c of b)c.remove();a=[...a.querySelectorAll(".devsite-nav-text > mark")];for(const c of a)a=c.parentElement,b=a==null?void 0:a.textContent,a&&b&&_ds.ug(a,
_ds.Yg(b))}},Pra=function(a,b){if(a=a.querySelector(".devsite-nav-text")){var c,d=(c=a.textContent)==null?void 0:c.replace(new RegExp(`(${b})`,"ig"),"<mark>$1</mark>");d&&_ds.ug(a,_ds.Yg(d))}},Qra=function(a,b){if(a=a.querySelector(".devsite-nav-text"))b=_ds.Gt(Kra,{JC:b}),a.appendChild(b)},Ora=async function(a,b){if(a.connected){var c=await _ds.w(),d=new _ds.bU,e=f=>{f=f.target;_ds.aU(d,f);a.oa.delete(f);c.unregisterIntersectionForElement(f)};for(const f of b)try{c.registerIntersectionForElement(f,
e)}catch(g){e({target:f})}}},G_=function(a,b){let c=!1;if(a.o)for(const d of a.o.querySelectorAll("[menu]"))d.getAttribute("menu")===b?(d.removeAttribute("hidden"),c=!0):_ds.cn(a,"hidden","",d);return c},P_=function(a,b=a){b||(b=a);for(const c of b.querySelectorAll(".devsite-nav-active"))c.classList.remove("devsite-nav-active"),c.removeAttribute("aria-current");a=_ds.bp(_ds.u().pathname);a=`[href="${_ds.Oo(a).href}"], [href="${a}"],
        [alt-paths~="${a}"]`;for(const c of b.querySelectorAll(a))c.classList.add("devsite-nav-active"),_ds.Sy(c,"current","page")},Q_=function(a,b=a){b||(b=a);if(a=b.querySelector(".devsite-mobile-nav-bottom"))for(a=a.querySelector(".devsite-nav-active");a&&a.parentElement&&a.parentElement!==b;)a.matches(".devsite-expandable-nav:not(.expanded)")&&a.classList.add("expanded"),a=a.parentElement},Rra=async function(a){a.connected&&(a.removeAttribute("user-scrolled"),await _ds.Vo(),await R_(a),await a.Aa,
await _ds.w(),await _ds.Vo(),await R_(a))},R_=async function(a){if(a.connected&&a.o){await _ds.w();var b=a.o.querySelector(".devsite-nav-active");b&&(a.hasAttribute("user-scrolled")||await Sra(a,b))}},Sra=async function(a,b){if(a.connected){var c=a.hasAttribute("user-scrolled");a.scrollTop=_ds.Jq(b,a,!0).y;await _ds.Vo();c&&_ds.cn(a,"user-scrolled","")}},S_=class extends _ds.fn{static get observedAttributes(){return["collapsed","fixed","hidden"]}constructor(){super();this.connected=!1;this.qa=this.m=
this.ra=this.o=null;this.ua=[];this.eventHandler=new _ds.v;this.va=()=>{};this.oa=new Set;_ds.bn(this,this.ma`animatable`,this.ma`aria-expanded`,this.ma`aria-label`,this.ma`collapsed`,this.ma`data-title`,this.ma`fixed`,this.ma`has-book-nav`,this.ma`hidden`,this.ma`top-level-nav`,this.ma`user-scrolled`,this.ma`visually-hidden`);this.background=document.createElement("div");this.background.classList.add("devsite-book-nav-bg");this.j=_ds.Gt(Ira);this.ea=_ds.Gt(Jra);this.Aa=new Promise(a=>{this.va=a});
this.xa=new _ds.fi(()=>{this.connected&&C_(this)},20);this.Ba=new _ds.fi(()=>{N_(this)},20);this.Ea=new _ds.fi(()=>{Mra(this)},100)}async connectedCallback(){this.connected=!0;_ds.Qn(this.background,this);this.hasAttribute("hidden")&&(_ds.cn(this,"hidden","",this.j),_ds.cn(this,"hidden","",this.ea));let a;(a=this.parentElement)==null||a.insertBefore(this.j,this.nextSibling);_ds.cn(this,"aria-label","Ocultar navega\u00e7\u00e3o lateral",this.j);_ds.cn(this,"data-title","Ocultar navega\u00e7\u00e3o lateral",
this.j);_ds.cn(this,"aria-expanded","true",this.j);let b;(b=this.parentElement)==null||b.insertBefore(this.ea,this.nextSibling);if(this.ra=this.querySelector(".devsite-book-nav-filter"))this.m=this.ra.querySelector("input[type=text]"),this.qa=this.ra.querySelector(".filter-clear-button"),M_(this),O_(this);C_(this);Nra(this);await this.init();K_(this)}disconnectedCallback(){this.connected=!1;_ds.G(this.eventHandler);L_(this);this.oa.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&
_ds.cn(this,"visually-hidden","",a);a=[this.background,this.j,this.ea];for(const b of a)b&&_ds.Sn(b);this.removeAttribute("animatable");this.background.removeAttribute("animatable");this.ea.removeAttribute("animatable");this.ea.style.removeProperty("--devsite-js-book-nav-scrollbar-width")}attributeChangedCallback(a){a==="hidden"&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if(a==="hidden"||a==="collapsed"){var b=
document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.cn(this,"has-book-nav","",b))}if(a==="fixed"||a==="hidden"||a==="collapsed"){b=this.hasAttribute(a);const c=[this.background,this.j,this.ea];for(const d of c)d&&(b?_ds.cn(this,a,"",d):d.removeAttribute(a))}a==="fixed"&&this.va()}async init(a=!0){if(this.connected){this.ea.style.setProperty("--devsite-js-book-nav-scrollbar-width",`${this.offsetWidth-
this.clientWidth}px`);this.o=this.querySelector(".devsite-mobile-nav-bottom");_ds.cn(this,"top-level-nav","");this.o&&this.o.querySelector("[menu=_book]")&&this.removeAttribute("top-level-nav");this.children.length===0&&_ds.cn(this,"hidden","");if(this.background)for(const b of["hidden","fixed","animatable"])this.hasAttribute(b)&&_ds.cn(this,b,"",this.background);!this.hasAttribute("hidden")&&a?(P_(this),Q_(this),await Rra(this)):(await _ds.Vo(),await R_(this))}}async fc(a){a?(a=a.querySelector("nav")||
null,P_(this,a),Q_(this,a),a&&(await L_(this),this.oa.clear(),K_(this,a,!1)),_ds.en(this,this.querySelector("nav"),a)):_ds.Pn(this);M_(this);if(this.m){this.m.value="";let b;(b=this.qa)==null||b.classList.add("hidden");O_(this)}await _ds.Vo();await this.init(!1)}};S_.prototype.updateContent=S_.prototype.fc;S_.prototype.attributeChangedCallback=S_.prototype.attributeChangedCallback;S_.prototype.disconnectedCallback=S_.prototype.disconnectedCallback;S_.prototype.connectedCallback=S_.prototype.connectedCallback;try{customElements.define("devsite-book-nav",S_)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
